# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  examportal:
    image: examportal
    build:
      context: .
      dockerfile: ExamPortal/Dockerfile
    ports:
      - 5000:5000
