name: BuildBackend
on:
  push:
    paths-ignore:
      - 'ExamPortal/ClientApp/**'
      - '.github/**'

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [5.0.201]
    
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v2
      - uses: NuGet/setup-nuget@v1.0.5
        with:
          nuget-version: 'latest'
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
          
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: resharper
        uses: glassechidna/resharper-action@master
        with:
          solution: ExamPortal.sln
          
